apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::969098148594:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UEFE48TLH6D3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::969098148594:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-18T13:53:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1498"
  uid: 6d2f1c32-5c6a-4609-aa63-5e2bebbb5819
